# Generated by Django 3.0.2 on 2020-04-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btntapp', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='dob',
            new_name='Date_Of_Birth',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='fname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lname',
            new_name='Last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
    ]
