# Generated by Django 3.0.2 on 2020-04-03 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('btntapp', '0003_auto_20200403_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=30),
        ),
    ]
