# Generated by Django 3.0.2 on 2020-04-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btntapp', '0004_auto_20200403_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
